### ISSUE TITLE
Could this simulate electrostatic repulsion and springs between particles?

### ISSUE THREAD

**Issue by nicx256** [Canleskis/particular#20]
I'd like to use a [force-directed layout](https://en.wikipedia.org/wiki/Force-directed_graph_drawing) algorithm to draw diagrams of graphs, is this crate likely to be a good basis for that? (Particles repel by Coulomb's law, attract by Hooke's law.)

Oh, just thought of a second question: i'd like my program to work on my old laptop which doesn't support compute shaders, so can this crate's Barnes-Hut implementation run CPU side?

**Comment by Canleskis** [comment]
Hi, the last released version (0.7.0) would allow for this but it would be a bit clunky to add interactions like Coulomb's law and Hooke's law. With the version that's work in progress in the main branch, you could absolutely implement these laws quite easily and make them work with the various algorithms. Check out the [`Interaction`](https://github.com/Canleskis/particular/blob/main/particular/src/lib.rs#L364) trait's documentation as well as the algorithm-specific similarly named traits.
Do note though that this library focuses simply on the computation of interactions between particles, so I imagine you would have to use your own data structures to represent something like a force-directed graph. The provided tree implementation is very simple and only designed to be fast to build.

Regarding your second question, the Barnes-Hut implementation is run on the CPU, although you can choose to run it in parallel.

**Comment by nicx256** [comment]
Thanks for responding! After posting my questions i checked the docs for the main branch version and saw that it has everything i'd hoped for (for the particle sim part of the problem, at least).

I'm not at all certain i'll be using enough particles to justify the approximating tree approach over just brute-forcing it, but wanted to have the option so was researching quad-trees. The tree implementation being simple is a plus, in case i want to try something fancy, like zooming in on a small region of a large graph vizualization and only simulating that area at high fidelity, or something.
