### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by Reklle** [Canleskis/particular#21]
I want to use particular in my project, but there is serious problems with demos for v7.0.0
```
use particular::prelude::*;
use particular::gravity::newtonian::Acceleration;
```
failed to resolve: could not find `gravity` in `particular`

---
I really don't understand what's wrong with it.
:-(

**Comment by Canleskis** [comment]
The documentation you're referring to is for the development version 0.8.0 in the main branch. Check the [latest](https://github.com/Canleskis/particular/tree/latest) branch for the documentation relative to 0.7.0 or alternatively you can setup particular to use the current main branch in your cargo.toml.
